name: Rust CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          profile: minimal

      - name: Install dependencies
        run: cargo fetch

      - name: Build
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Determine next version
        id: version
        uses: mgoltzsche/conventional-release@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-release: true
          release-branch: main
          ignore-commits-before: "187470a1bc94c2e5671e0b6a4b1fd7c0b08be2e8"
          update-major-tag: false
          github-release-enabled: true
          github-release-draft: false
          github-release-latest: true
          ref: refs/heads/main

      - name: Check if tag already exists
        run: |
          if git rev-parse "refs/tags/v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.version.outputs.version }} already exists. Skipping release."
            exit 0
          fi

      - name: Update Cargo.toml version
        if: steps.version.outputs.publish == 'true'
        run: |
          VERSION=${{ steps.version.outputs.version }}
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Cargo.toml
          git commit -m "chore: bump version to $VERSION"
          git push origin main

      - name: Create GitHub Release
        if: steps.version.outputs.publish == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          files: target/release/your_actual_executable_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
